# Generated by Django 3.2 on 2023-02-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='Почта')),
                ('author', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=3000, verbose_name='Описание')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('blocked', 'Заблокированно')], default='active', max_length=300, verbose_name='Статус')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время и дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время и дата обновления')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книга',
            },
        ),
    ]
